imports:
    - { resource:  parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cooolinho\App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Cooolinho\App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
