services:
    _defaults:
        autowire: true
        autoconfigure: true

    Cooolinho\TestBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Resources,Tests}'

    Cooolinho\TestBundle\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']
