security:
    encoders:
        Cooolinho\SecurityBundle\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: Cooolinho\SecurityBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - Cooolinho\SecurityBundle\Security\SecurityAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
