twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/cooolinho/ui-bundle/src/Resources/views': ui
    form_themes: ['bootstrap_4_layout.html.twig']
